---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: imageservice-shadow
  namespace: bazaar-shadow
spec:
  host: aes-demo.com
  prefix: /image/
  service: imageservice.bazaar:80
  shadow: true
  weight: 10
---