---
apiVersion: v1
kind: Service
metadata:
  name: imageservice-shadow
  namespace: bazaar-shadow
spec:
  selector:
    app: imageapp-shadow
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---