---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice-shadow
  namespace: bazaar-shadow
  labels:
    app: inventoryapp-shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryapp-shadow
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      labels:
        app: inventoryapp-shadow
    spec:
      containers:
        - name: inventoryservice-shadow
          image: docker.io/brucehorn/ambassador_service_preview_demo-inventoryservice:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
---