---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: specsservice-shadow
  namespace: bazaar-shadow
  labels:
    app: specsapp-shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: specsapp-shadow
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      labels:
        app: specsapp-shadow
    spec:
      containers:
        - name: specsservice-shadow
          image: docker.io/brucehorn/ambassador_service_preview_demo-specsservice:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
---